spring:
  datasource:
    url: jdbc:mariadb://192.168.20.106:3306/modnpay?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: modnpay
    password: modnpay_pwd!
    hikari:
      max-lifetime: 58000 #DB wait_timeout=60
      idle-timeout: 58000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
    properties:
      hibernate:
        show_sql: false
