# 로컬 개발환경 설정
# 1. 인메모리 db 빌드, 2. table create ,3. 테스트 데이터 insert, 4. 필요에 따라 flush, clear 실행.
server:
  port: 8888

spring:
  security:
    # InMemoryReactiveClientRegistrationRepository 구성
    # ReactiveOAuth2ClientAutoConfiguration가 자동설정해준다.
    oauth2: # http://localhost:8888/oauth2/authorization/diamond -> 리다이렉트
      client: # 로그인 엔드포인트(/oauth2/authorization/{registration명}) 접근시 서드파티 인증서버로 리다이랙트해줌, 리다이렉션 엔드포인트(/login/oauth2/code/{registration명}) 자동생성
        registration: # ClientRegistration : Provider에 등록된 클라이언트를 표현하는 객체
          diamond: # 클라이언트 id CommonOAuth2Provider는 잘알려진 client속성 미리 정의해둔거
            provider: nawabari
            client-id: diamond
            client-secret: frJg59COB69s6wg2ENhMHTOCeyd5SK6R
            scope: openid, profile, email # OpenID Connect 1.0을 사용하겠다. OIDC 전용 컴포넌트(예: OidcReactiveOAuth2UserService)를 사용
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          nawabari:
#            authorization-uri: http://localhost:8080/realms/nawabari/protocol/openid-connect/auth
#            token-uri: http://localhost:8080/realms/nawabari/protocol/openid-connect/token
#            user-info-uri: http://localhost:8080/realms/nawabari/protocol/openid-connect/userinfo
#            user-info-authentication-method: header
#            user-name-attribute: preferred_username
#            jwk-set-uri: http://localhost:8080/realms/nawabari/protocol/openid-connect/certs
            # ⚠️ issuer-uri는 절대 넣지 말 것 (넣는 순간 Keycloak metadata 파싱 → mtls 오류 재발)
             issuer-uri: http://localhost:8080/realms/nawabari   # ❌ 주석 유지
  redis:
    host: localhost
    port: 6379
  session:
    redis:
      namespace: "spring:session:diamond"
    store-type: redis



  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5     # max보다 작게
      max-lifetime: 180000
      idle-timeout: 60000  # 1분 (원하면 유지)
  batch:
    job:
      enabled: false
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: modnpay-batch-scheduler2
            instanceId: AUTO
            makeSchedulerThreadDaemon: true
            interruptJobsOnShutdown: true
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: false
            clusterCheckinInterval: 20000
            misfireThreshold: 60000
            tablePrefix: QRTZ_
            isClustered: true
        threadPool:
          makeThreadsDaemons: true
          threadCount: 5
#  h2:
#    console:
#      enabled: false
  jpa:
    show-sql: true        # SQL 출력
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties: # Difference between spring.jpa.properties.hibernate and spring.jpa.hibernate
      hibernate:
        ddl-auto: none
        format_sql: true   # 보기 좋게 포맷팅

logging:
  level:
    org.hibernate.SQL: debug           # SQL 로그
    org.hibernate.type.descriptor.sql: trace   # 바인딩된 파라미터 값 출력
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE


# 로그 레벨: 쿼리 로그는 DEBUG, 슬로우쿼리는 WARN 으로 떨어집니다.
#logging:
#  level:
#    net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener: DEBUG
#    net.ttddyy.dsproxy.listener.logging.SLF4JSlowQueryListener: WARN

# datasource-proxy 옵션 (스타터가 노출하는 설정)
#decorator:
#  datasource:
#    datasource-proxy:
#      multiline: true                  # 여러 줄 포맷
#      format-sql: true                 # SQL 포매팅(하이버네이트 포매터 감지)
#      json-format: false               # JSON 포맷(원하면 true)
#      slow-query:
#        enable-logging: true
#        log-level: warn
#        threshold: 300                 # ms 단위 (예: 300ms 이상 슬로우)
