services:
  source:
    image: mysql:8.0
    container_name: source
    ports: ["3307:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mall
      MYSQL_ROOT_HOST: "%"
    command:
      - --default-authentication-plugin=mysql_native_password
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./source/conf.d:/etc/mysql/conf.d  # 로컬 ./conf.d 안의 모든 *.cnf를 컨테이너 /etc/mysql/conf.d 로
      - ./source/init:/docker-entrypoint-initdb.d

  replica:
    image: mysql:8.0
    container_name: replica
    ports: ["3308:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      TZ: Asia/Seoul
    command:
      - --default-authentication-plugin=mysql_native_password
    depends_on: [source]
    volumes:
      - ./replica1/source.cnf:/etc/mysql/conf.d/source.cnf # 파일복사
      - ./replica1/01-replication.sql:/docker-entrypoint-initdb.d/01-replication.sql # 파일복사
    networks: [replnet]

networks:
  replnet: {}


#  docker compose down -v   # 컨테이너와 볼륨 모두 삭제 (데이터 날아감)
#  docker compose up -d     # 다시 올리면 환경변수 적용된 상태로 DB 초기화